In [1]:
import pandas as pd
import sqlalchemy as sql
from sqlalchemy import create_engine

# Extract CSVs into DataFrames

In [64]:
SCAthletic_file = "./Output/ShopComAthletic.csv"
SCAthletic_df = pd.read_csv(SCAthletic_file)
SCAthletic_df.head()

,Unnamed: 0,ProductID,Price,Name,Brand,Gender,Image,URL
0,0,1855904262,185.800,Cougar Women's Vienna-S In Black,Cougar,Women,https://img.shop.com/Image/260000/267800/26787...,https://www.shop.com/cougar-womens-vienna-s-in...
1,1,1860265708,119.095,Sam Edelman Women's Pippy Gold M,Sam Edelman,Women,https://img.shop.com/Image/260000/267800/26787...,https://www.shop.com/sam-edelman-womens-pippy-...
2,2,1820031831,128.390,Tretorn Women's Rawlins 10 in Black,Tretorn,Women,https://img.shop.com/Image/260000/267800/26787...,https://www.shop.com/tretorn-womens-rawlins-10...
3,3,1869256932,54.480,Steve Madden Womens Tracey Faux Leather Lace-u...,Steve Madden,Women,https://img.shop.com/Image/270000/273200/27320...,https://www.shop.com/steve-madden-womens-trace...
4,4,1881421772,78.820,Andrea Conti Women's Dani in White,NaN,Women,https://img.shop.com/Image/260000/267800/26787...,https://www.shop.com/andrea-conti-womens-dani-...

# Transform SCAthletic_df

In [69]:
#Clean dataframe to match sql schema
SCAthletic_dfClean = SCAthletic_df.drop(['Unnamed: 0', 'ProductID', 'Brand', 'Image'], axis = 1)
SCAthletic_dfClean = SCAthletic_dfClean.reset_index()
SCAthletic_dfClean = SCAthletic_dfClean.rename(columns = {'index':'ID'})
SCAthletic_dfClean = SCAthletic_dfClean[['ID', 'Name', 'Price', 'Gender', 'URL']]
SCAthletic_dfClean

,ID,Name,Price,Gender,URL
0,0,Cougar Women's Vienna-S In Black,185.800,Women,https://www.shop.com/cougar-womens-vienna-s-in...
1,1,Sam Edelman Women's Pippy Gold M,119.095,Women,https://www.shop.com/sam-edelman-womens-pippy-...
2,2,Tretorn Women's Rawlins 10 in Black,128.390,Women,https://www.shop.com/tretorn-womens-rawlins-10...
3,3,Steve Madden Womens Tracey Faux Leather Lace-u...,54.480,Women,https://www.shop.com/steve-madden-womens-trace...
4,4,Andrea Conti Women's Dani in White,78.820,Women,https://www.shop.com/andrea-conti-womens-dani-...
...,...,...,...,...,...
8196,8196,Puma Suede PS 50th Gold Gold 367295-01 Kid's,52.000,Boys,https://www.shop.com/puma-suede-ps-50th-gold-g...
8197,8197,Puma Minions Basket Tongue White-Black-Minion ...,52.000,Boys,https://www.shop.com/puma-minions-basket-tongu...
8198,8198,Puma Suede Heart PS Desert Flower/White 36501...,52.000,Boys,https://www.shop.com/puma-suede-heart-ps-deser...
8199,8199,New Balance KL574AIP Grey/Purple/Teal KL574AI...,35.000,Boys,https://www.shop.com/new-balance-kl574aip-grey...
8200,8200,New Balance KL574C8G Black/White KL574C8G Kid's,68.000,Boys,https://www.shop.com/new-balance-kl574c8g-blac...

# Create database connection

In [24]:
connection_string = "postgres:Payrol662!@localhost:5433/FootwearFinder_db"
engine = create_engine(f'postgresql://{connection_string}')
sql.inspect(engine).get_columns('shopcom')

[{'name': 'id',
  'type': INTEGER(),
  'nullable': False,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'name',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'price',
  'type': DOUBLE_PRECISION(precision=53),
  'nullable': True,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'gender',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'url',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'autoincrement': False,
  'comment': None}]

# Load DataFrames into database

In [61]:
SCAthletic_dfClean.to_sql(name='shopcom', con=engine, if_exists='append', index=False)